/**
 * GENERATED — DO NOT EDIT BY HAND
 *
 * This file is regenerated by `npm run codegen:api`, which runs
 * `openapi-typescript` against the live backend's `/openapi.json`
 * document and writes the typed schema here.
 *
 * Workflow:
 *
 *   1. Start the backend in dev mode:
 *        cd backend
 *        FPULSE_MODE=dev python -m uvicorn fpulse.main:app --port 8001
 *      (OpenAPI is auto-enabled when FPULSE_MODE=dev.)
 *
 *   2. In a second terminal:
 *        cd frontend
 *        npm run codegen:api
 *
 *   3. Commit the regenerated file alongside the route changes that
 *      produced it. Frontend type errors on the next `npm run build`
 *      will catch routes whose response shapes drifted.
 *
 * Until you've run the codegen at least once, this stub keeps the
 * imports resolvable. Replace nothing manually — re-run codegen.
 */

export interface paths {}
export interface components {
  schemas: {};
}
export type operations = Record<string, never>;
