#!/usr/bin/env bash
# installer/linux/build-rpm.sh
#
# Build the F-Pulse RPM package.
#
# Output target distros: Fedora 39+, RHEL/Alma/Rocky 9+, openSUSE 15.5+.
#
# Prereqs (one-time):
#   sudo dnf install rpm-build rpmdevtools python3 nodejs npm
#   And a Python 3.12+ venv at <repo>/.venv with pyinstaller installed.
#
# Usage:
#   ./build-rpm.sh
#
# Output:
#   installer/linux/output/fpulse-<version>-1.x86_64.rpm

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
# Read the version from pyproject.toml rather than hardcoding it — a stale
# literal here silently ships a package whose filename and metadata disagree
# with the code inside it.
VERSION="$(grep -m1 -E '^version = "' "$REPO_ROOT/pyproject.toml" | sed -E 's/^version = "([^"]+)"/\1/')"
[[ -n "$VERSION" ]] || { echo "could not read version from pyproject.toml"; exit 1; }
RELEASE="1"
ARCH="x86_64"
PKG_NAME="fpulse"

echo
echo "  F-Pulse .rpm build"
echo "  Repo:    $REPO_ROOT"
echo "  Version: $VERSION-$RELEASE.$ARCH"
echo

BUILD_DIR="$SCRIPT_DIR/build/rpm"
OUTPUT_DIR="$SCRIPT_DIR/output"
BUILDROOT="$BUILD_DIR/BUILDROOT/$PKG_NAME-$VERSION-$RELEASE.$ARCH"

rm -rf "$BUILD_DIR"
mkdir -p "$OUTPUT_DIR" \
         "$BUILD_DIR/BUILD" \
         "$BUILD_DIR/RPMS" \
         "$BUILD_DIR/SOURCES" \
         "$BUILD_DIR/SPECS" \
         "$BUILD_DIR/SRPMS" \
         "$BUILDROOT/usr/lib/$PKG_NAME" \
         "$BUILDROOT/usr/bin" \
         "$BUILDROOT/usr/share/applications" \
         "$BUILDROOT/usr/share/doc/$PKG_NAME" \
         "$BUILDROOT/usr/share/icons/hicolor/256x256/apps"

# ── 1. Frontend ──
# Build it, then STAGE it into the Python package. PyInstaller's
# `--collect-all fpulse` below picks up backend/fpulse/frontend_dist/, so the
# frozen bundle carries the UI where main.py actually looks for it
# (fpulse/frontend_dist). Without staging, the app resolves no UI and serves
# a 404 at / — it will say so loudly at startup.
echo "  [1/4] Building + staging frontend..."
( cd "$REPO_ROOT/frontend" && npm install --silent && npm run build )
"$REPO_ROOT/.venv/bin/python" "$REPO_ROOT/scripts/stage_frontend.py"

# ── 2. Freeze backend ──
echo "  [2/4] Freezing backend with PyInstaller..."
PYTHON="$REPO_ROOT/.venv/bin/python"
[[ -x "$PYTHON" ]] || { echo "Python venv not found at $PYTHON"; exit 1; }

( cd "$REPO_ROOT" && \
  "$PYTHON" -m PyInstaller \
    --onedir --noconfirm --clean \
    --name fpulse \
    --paths backend \
    --hidden-import fpulse.main \
    --collect-all fpulse \
    --collect-all duckdb \
    --collect-all fastapi \
    --collect-all uvicorn \
    --distpath "$BUILDROOT/usr/lib/$PKG_NAME/runtime" \
    backend/fpulse/__main__.py )

# NOTE: no separate frontend copy here. Older revisions copied frontend/dist
# to .../frontend-dist, which main.py never looks for — the package installed
# cleanly and served a blank page. The UI now travels inside the PyInstaller
# bundle via the staging step above.

# Verify the frozen bundle actually carries the UI, rather than discovering it
# after the package is on someone's machine.
if ! find "$BUILDROOT/usr/lib/$PKG_NAME/runtime" -path '*/fpulse/frontend_dist/index.html' -print -quit | grep -q .; then
  echo "ERROR: the PyInstaller bundle has no fpulse/frontend_dist/index.html."
  echo "       The package would install and serve a blank page. Refusing to build."
  exit 1
fi
ln -sf "/usr/lib/$PKG_NAME/runtime/fpulse/fpulse" "$BUILDROOT/usr/bin/fpulse"

cat > "$BUILDROOT/usr/share/applications/fpulse.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=F-Pulse
GenericName=Data Pipeline Studio
Comment=Build, run, and schedule data pipelines locally
Exec=xdg-open http://localhost:8001
Icon=fpulse
Terminal=false
Categories=Development;Database;
EOF

# Brand icon for the Icon=fpulse entry above (build-deb / build-appimage
# read the same shared PNG). Generated by installer/windows/make-icon.ps1.
cp "$SCRIPT_DIR/../windows/icons/fpulse.png" \
   "$BUILDROOT/usr/share/icons/hicolor/256x256/apps/fpulse.png"

cp "$REPO_ROOT/README.md"  "$BUILDROOT/usr/share/doc/$PKG_NAME/"
cp "$REPO_ROOT/LICENSE"    "$BUILDROOT/usr/share/doc/$PKG_NAME/LICENSE"
[[ -f "$REPO_ROOT/NOTICE" ]] && cp "$REPO_ROOT/NOTICE" "$BUILDROOT/usr/share/doc/$PKG_NAME/"

# ── 3. Generate spec file ──
echo "  [3/4] Writing .spec file..."
SPEC="$BUILD_DIR/SPECS/$PKG_NAME.spec"
cat > "$SPEC" <<EOF
# We ship a PyInstaller bundle: a self-contained tree of vendored .so files
# that rpm's post-processing was never meant to inspect. Three of its default
# behaviours have to be switched off, or the build fails on shipped upstream
# artifacts we do not control:
#
#   _build_id_links none
#     PyInstaller vendors both libarrow_python.so and libarrow_python.so.2500.0.0
#     — the same object under two names, so the same build-id. rpm treats that
#     as a hard error ("Duplicate build-ids"). We are not a system library
#     provider; nobody resolves debuginfo against these.
#   debug_package %%{nil}
#     No separate -debuginfo subpackage for a frozen bundle.
#   __brp_strip / __brp_strip_static_archive
#     Stripping PyInstaller's binaries can break them; leave them intact.
%global _build_id_links none
%global debug_package %%{nil}
%global __brp_strip %%{nil}
%global __brp_strip_static_archive %%{nil}

Name:           $PKG_NAME
Version:        $VERSION
Release:        $RELEASE%{?dist}
Summary:        F-Pulse OSS — local-first data pipeline studio
License:        Apache-2.0
URL:            https://hybridyn.com/f-pulse
BuildArch:      $ARCH
AutoReqProv:    no
Requires:       glibc, libstdc++
Recommends:     xdg-utils

%description
F-Pulse OSS is a self-hosted, local-first data pipeline tool by
Hybridyn Data Labs. Build, schedule, and observe ETL/ELT pipelines from a
browser UI on your own machine — no cloud account required.

Includes a frozen Python runtime, so no system Python is needed.
The service is registered as a systemd --user unit on first launch
so it auto-starts when you log in.

%files
/usr/bin/fpulse
/usr/lib/$PKG_NAME/
/usr/share/applications/fpulse.desktop
/usr/share/icons/hicolor/256x256/apps/fpulse.png
%doc /usr/share/doc/$PKG_NAME/README.md
%doc /usr/share/doc/$PKG_NAME/LICENSE
# NOTICE is copied above and MUST be listed, or rpmbuild aborts with
# "Installed (but unpackaged) file(s) found". It is also an Apache-2.0
# redistribution requirement, so dropping the copy is not the fix.
%doc /usr/share/doc/$PKG_NAME/NOTICE

%post
# %post runs as root with no \$SUDO_USER available — print
# directions instead of trying to guess the target user.
echo ""
echo "  F-Pulse installed. To start the service as your user:"
echo "    fpulse install-service"
echo "    sudo loginctl enable-linger \\\$USER"
echo "  Then open http://localhost:8001"
echo ""

%preun
# Best-effort stop. The systemd --user unit lives under each user's
# home dir, so we can't authoritatively stop it from the root RPM
# scriptlet — but we try the common case.
if [ -n "\${SUDO_USER:-}" ] && [ "\$SUDO_USER" != "root" ]; then
  su - "\$SUDO_USER" -c "/usr/bin/fpulse uninstall-service" || true
fi
exit 0

%changelog
* $(date '+%a %b %d %Y') Hybridyn <support@hybridyn.com> - $VERSION-$RELEASE
- Release $VERSION
EOF

# ── 4. Build the .rpm ──
echo "  [4/4] rpmbuild..."
rpmbuild \
  --define "_topdir $BUILD_DIR" \
  --define "_rpmdir $BUILD_DIR/RPMS" \
  --define "_buildrootdir $BUILD_DIR/BUILDROOT" \
  --define "buildroot $BUILDROOT" \
  --noclean \
  -bb "$SPEC"

# Move the result out where users expect it
RPM_FILE="$(find "$BUILD_DIR/RPMS" -name '*.rpm' | head -n 1)"
[[ -n "$RPM_FILE" ]] || { echo "rpmbuild produced no .rpm file"; exit 1; }
cp "$RPM_FILE" "$OUTPUT_DIR/"

OUT="$OUTPUT_DIR/$(basename "$RPM_FILE")"

# Optional GPG sign
if [[ -n "${FPULSE_GPG_KEY_ID:-}" ]] && command -v rpmsign >/dev/null 2>&1; then
  echo "  Signing with GPG key $FPULSE_GPG_KEY_ID..."
  rpmsign --define "_gpg_name $FPULSE_GPG_KEY_ID" --addsign "$OUT"
fi

echo
echo "  Done. Output: $OUT"
echo "  Install with: sudo dnf install $OUT"
echo
