#!/usr/bin/env bash
# installer/linux/build-rpm.sh
#
# Build the F-Pulse RPM package.
#
# Output target distros: Fedora 39+, RHEL/Alma/Rocky 9+, openSUSE 15.5+.
#
# Prereqs (one-time):
#   sudo dnf install rpm-build rpmdevtools python3 nodejs npm
#   And a Python 3.12+ venv at <repo>/.venv with pyinstaller installed.
#
# Usage:
#   ./build-rpm.sh
#
# Output:
#   installer/linux/output/fpulse-<version>-1.x86_64.rpm

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
VERSION="1.0.0"
RELEASE="1"
ARCH="x86_64"
PKG_NAME="fpulse"

echo
echo "  F-Pulse .rpm build"
echo "  Repo:    $REPO_ROOT"
echo "  Version: $VERSION-$RELEASE.$ARCH"
echo

BUILD_DIR="$SCRIPT_DIR/build/rpm"
OUTPUT_DIR="$SCRIPT_DIR/output"
BUILDROOT="$BUILD_DIR/BUILDROOT/$PKG_NAME-$VERSION-$RELEASE.$ARCH"

rm -rf "$BUILD_DIR"
mkdir -p "$OUTPUT_DIR" \
         "$BUILD_DIR/BUILD" \
         "$BUILD_DIR/RPMS" \
         "$BUILD_DIR/SOURCES" \
         "$BUILD_DIR/SPECS" \
         "$BUILD_DIR/SRPMS" \
         "$BUILDROOT/usr/lib/$PKG_NAME" \
         "$BUILDROOT/usr/bin" \
         "$BUILDROOT/usr/share/applications" \
         "$BUILDROOT/usr/share/doc/$PKG_NAME" \
         "$BUILDROOT/usr/share/icons/hicolor/256x256/apps"

# ── 1. Frontend ──
echo "  [1/4] Building frontend..."
( cd "$REPO_ROOT/frontend" && npm install --silent && npm run build )

# ── 2. Freeze backend ──
echo "  [2/4] Freezing backend with PyInstaller..."
PYTHON="$REPO_ROOT/.venv/bin/python"
[[ -x "$PYTHON" ]] || { echo "Python venv not found at $PYTHON"; exit 1; }

( cd "$REPO_ROOT" && \
  "$PYTHON" -m PyInstaller \
    --onedir --noconfirm --clean \
    --name fpulse \
    --paths backend \
    --hidden-import fpulse.main \
    --collect-all fpulse \
    --collect-all duckdb \
    --collect-all fastapi \
    --collect-all uvicorn \
    --distpath "$BUILDROOT/usr/lib/$PKG_NAME/runtime" \
    backend/fpulse/__main__.py )

cp -R "$REPO_ROOT/frontend/dist" "$BUILDROOT/usr/lib/$PKG_NAME/frontend-dist"
ln -sf "/usr/lib/$PKG_NAME/runtime/fpulse/fpulse" "$BUILDROOT/usr/bin/fpulse"

cat > "$BUILDROOT/usr/share/applications/fpulse.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=F-Pulse
GenericName=Data Pipeline Studio
Comment=Build, run, and schedule data pipelines locally
Exec=xdg-open http://localhost:8001
Icon=fpulse
Terminal=false
Categories=Development;Database;
EOF

# Brand icon for the Icon=fpulse entry above (build-deb / build-appimage
# read the same shared PNG). Generated by installer/windows/make-icon.ps1.
cp "$SCRIPT_DIR/../windows/icons/fpulse.png" \
   "$BUILDROOT/usr/share/icons/hicolor/256x256/apps/fpulse.png"

cp "$REPO_ROOT/README.md"  "$BUILDROOT/usr/share/doc/$PKG_NAME/"
cp "$REPO_ROOT/LICENSE"    "$BUILDROOT/usr/share/doc/$PKG_NAME/LICENSE"
[[ -f "$REPO_ROOT/NOTICE" ]] && cp "$REPO_ROOT/NOTICE" "$BUILDROOT/usr/share/doc/$PKG_NAME/"

# ── 3. Generate spec file ──
echo "  [3/4] Writing .spec file..."
SPEC="$BUILD_DIR/SPECS/$PKG_NAME.spec"
cat > "$SPEC" <<EOF
Name:           $PKG_NAME
Version:        $VERSION
Release:        $RELEASE%{?dist}
Summary:        F-Pulse OSS — local-first data pipeline studio
License:        Apache-2.0
URL:            https://hybridyn.com/f-pulse
BuildArch:      $ARCH
AutoReqProv:    no
Requires:       glibc, libstdc++
Recommends:     xdg-utils

%description
F-Pulse OSS is a self-hosted, local-first data pipeline tool by
Hybridyn. Build, schedule, and observe ETL/ELT pipelines from a
browser UI on your own machine — no cloud account required.

Includes a frozen Python runtime, so no system Python is needed.
The service is registered as a systemd --user unit on first launch
so it auto-starts when you log in.

%files
/usr/bin/fpulse
/usr/lib/$PKG_NAME/
/usr/share/applications/fpulse.desktop
/usr/share/icons/hicolor/256x256/apps/fpulse.png
%doc /usr/share/doc/$PKG_NAME/README.md
%doc /usr/share/doc/$PKG_NAME/LICENSE

%post
# %post runs as root with no \$SUDO_USER available — print
# directions instead of trying to guess the target user.
echo ""
echo "  F-Pulse installed. To start the service as your user:"
echo "    fpulse install-service"
echo "    sudo loginctl enable-linger \\\$USER"
echo "  Then open http://localhost:8001"
echo ""

%preun
# Best-effort stop. The systemd --user unit lives under each user's
# home dir, so we can't authoritatively stop it from the root RPM
# scriptlet — but we try the common case.
if [ -n "\${SUDO_USER:-}" ] && [ "\$SUDO_USER" != "root" ]; then
  su - "\$SUDO_USER" -c "/usr/bin/fpulse uninstall-service" || true
fi
exit 0

%changelog
* $(date '+%a %b %d %Y') Hybridyn <support@hybridyn.com> - $VERSION-$RELEASE
- Release $VERSION
EOF

# ── 4. Build the .rpm ──
echo "  [4/4] rpmbuild..."
rpmbuild \
  --define "_topdir $BUILD_DIR" \
  --define "_rpmdir $BUILD_DIR/RPMS" \
  --define "_buildrootdir $BUILD_DIR/BUILDROOT" \
  --define "buildroot $BUILDROOT" \
  --noclean \
  -bb "$SPEC"

# Move the result out where users expect it
RPM_FILE="$(find "$BUILD_DIR/RPMS" -name '*.rpm' | head -n 1)"
[[ -n "$RPM_FILE" ]] || { echo "rpmbuild produced no .rpm file"; exit 1; }
cp "$RPM_FILE" "$OUTPUT_DIR/"

OUT="$OUTPUT_DIR/$(basename "$RPM_FILE")"

# Optional GPG sign
if [[ -n "${FPULSE_GPG_KEY_ID:-}" ]] && command -v rpmsign >/dev/null 2>&1; then
  echo "  Signing with GPG key $FPULSE_GPG_KEY_ID..."
  rpmsign --define "_gpg_name $FPULSE_GPG_KEY_ID" --addsign "$OUT"
fi

echo
echo "  Done. Output: $OUT"
echo "  Install with: sudo dnf install $OUT"
echo
